### ISSUE TITLE
menu & toolbar not visible (Fedora 25)

### ISSUE THREAD

**Issue by gour** [martin-pe/maitreya7#7]
Hello,

recently I moved to Fedora 25 Linux and compiled Maitreya-7.1.1 (git's master) agains wx-3.0.2, but the problem is that the main menu and toolbar are not visible:

![maitreya-shot](https://cloud.githubusercontent.com/assets/114592/20936037/6ab24f9a-bbe1-11e6-8987-392c936202ec.png)

Any hint?

**Comment by martin-pe** [comment]
I know that on several Linuxes the toolbar did not appear. This is fixed in the current dev release. But no menu - don't know.
I'll try to compile on Fedora 25 if time permits, guess that this is a GTK bug.
You can compile with wx2.8 meanwhile - should work.
